### ISSUE TITLE
Write and Listen Page

### ISSUE THREAD

**Issue by triantac** [triantac/punkbuddy#2]
Writing everything in the order it appears
-Instructions to students (will write) later
-Text input box
Highlights text as it reads; options for fonts (OpenDyslexic & some sans-serif fonts, will let you know)
-Left side: Listen to your text (3) -> number of attempts counting down
After 3 attempts, the box is greyed out, arrow pointing to Check button (make check button appear after the 1st attempt if possible)

**Comment by lukel97** [comment]
I think this is mostly done now, leaving this open for when you have the instructions text
