### ISSUE TITLE
Updates in functionality 

### ISSUE THREAD

**Issue by triantac** [triantac/punkbuddy#5]
Adding changes here:

TTS
Number of attempts at TTS-> increase from 3 to 5
Can we make it so that the system tells you to listen to your text every 100 words you write?

Check page
I'm not sure if that's possible, but I would like to have some suggestions popping up for punctuation correction.
Suggestion text: "Maybe you should add a pause here."
Where: 
Before the words but, as, so, though, 
Before and after the words/phrases: instead, however, firstly, secondly, finally, ultimately, alternatively, eventually, in my opinion, in conclusion
_If possible:_
After adjectives (not sure if you can code that, probably not)
After salutations (dear diary, dear Sir, dear Madam, dear *name*, etc.)
If there is already a pause (comma, fullstop) before those, then we don't need the suggestion to pop up.

**Comment by triantac** [comment]
@bubba tagging you just in case you missed it; I thought it would be better to open two separate threads

**Comment by lukel97** [comment]
- [x] Fix weird delayed-by-one-word bug
- [x] Add regexes for the remainder of the words in this list

**Comment by lukel97** [comment]
Going to create a new issue for detecting adjectives, I think we can do it but we need to find a library for natural language processing
