### ISSUE TITLE
Changes in appearance

### ISSUE THREAD

**Issue by triantac** [triantac/punkbuddy#6]
Header: Write, Listen, Check (one tab)
About (second tab)
delete the practice tab
Header colour: #EDDD6E; 15.7:1 (colours taken from the paper here: https://dl.acm.org/doi/pdf/10.1145/3132525.3132546)
Font: black, a bit bigger if possible

Would be nice to be able to choose fonts
Togglable fonts: Arial, Open Dyslexic, Courier

Body
Title stays the same
Instructions: Welcome to PunkBuddy! Here, you can write your text, listen to it, and correct it.
Hoverable instructions (if possible, I would like these to be available when hovering on them): PunkBuddy reads your text for you. Listen to your text a few times and correct it. Then, PunkBuddy will check it for you. Do you hear any pauses? Do you need more pauses?
Speak button: replace text with "Listen to your text! (5 attempts left)"
Button colour: #96ADFC (https://dl.acm.org/doi/pdf/10.1145/3132525.3132546)
Make the check button appear after 3 attempts. Check button text: "Check your writing!" (same colour as the other button)

When Check your writing shows up:
Hoverable instructions: PunkBuddy checks your text for you. Take a look at the suggestions. Is your punctuation correct? What can you fix?

Also, for the check your writing part, I'd like the word count progress bar we had discussed. Shows total word count and also shows a progress bar for each sentence.
16 words: "Maybe you should finish your sentence soon."
20 words: "Your sentence is getting too long!"

**Comment by lukel97** [comment]
What's the 15.7:1 bit for the header?

**Comment by triantac** [comment]
oops sorry, copied it straight from the paper, you probably don't need it!

**Comment by lukel97** [comment]
For the instructions on the body part, which page should this appear on? The write/listen/check page or the about page? Or both?

**Comment by lukel97** [comment]
And I presume it should replace where the "Modi temporibus esse..." dummy text currently is?

**Comment by triantac** [comment]
"Welcome to PunkBuddy! Here, you can write your text, listen to it, and correct it." -> this appears on both

Listen: PunkBuddy reads your text for you. Listen to your text a few times and correct it. Then, PunkBuddy will check it for you. Do you hear any pauses? Do you need more pauses?

Check: PunkBuddy checks your text for you. Take a look at the suggestions. Is your punctuation correct? What can you fix?

And yes, it replaces the dummy text

Text for the About page: 
PunkBuddy is an artefact created at Trinity College Dublin by Luke Lau and Chara Triantafyllidou. It is part of the dissertation of Chara Triantafyllidou for the MPhil in Applied Linguistics, 2019-2020.
Its goal is to assist learners with writing and reading difficulties, as well as their parents and their English teachers. PunkBuddy yields the affordances of TTS technologies for proof-listening and uses a punctuation correction interface. Its design is informed by recent neurocognitive findings on prosodic processing and dyslexia, a perception test on punctuation, a text analysis of Junior Cycle textbooks, and the design of recent dyslexia software. 
Recommended for students in the final grade of Primary School onwards.

**Comment by triantac** [comment]
I hope all these make sense! If they don't, gimme angry reacts and let me know

**Comment by lukel97** [comment]
So just to confirm both write listen & check say "Welcome to PunkBuddy! Here, you can write your text, listen to it, and correct it.", but when hovered over have a popover that reads "PunkBuddy reads your text for you. Listen to your text a few times and correct it. Then, PunkBuddy will check it for you. Do you hear any pauses? Do you need more pauses?" and "PunkBuddy checks your text for you. Take a look at the suggestions. Is your punctuation correct? What can you fix?" respectively

**Comment by triantac** [comment]
yes that's it! I see in the current version that the popover instructions are also displayed in the other description.
Also, for the popover, could you replace the question mark with the word Instructions?
Forgot to mention a background colour for the main body: #EDD1B0 (sorry sorry sorry)

**Comment by lukel97** [comment]
I think this stuff is done now
